### ISSUE TITLE
rename repo for consistency and better cloning

### ISSUE THREAD

**Issue by vassudanagunta** [commonmark/markdownhelp#11]
The current repo name, `commonmark/web`, when cloned, i.e. `git clone https://github.com/commonmark/web.git`, results in a local repo named "web". 

It would be good to rename the CommonMark-site repo too. See issue commonmark/CommonMark-site#2.

A couple of suggested options:

current name | option 1 (semantic name) | option 2 (hosting domain name)
--------|---------|--------
commonmark/web | commonmark-web  | commonmark.org
CommonMark-site | commonmark-spec-web  | spec.commonmark.org

**Comment by coding-horror** [comment]
ok I'll rename the web one at least

**Comment by jgm** [comment]
CommonMark-site was already renamed commonmark-spec-web....

**Comment by waldyrious** [comment]
Related issue on the spec repo: https://github.com/commonmark/commonmark-spec-web/issues/2
