### ISSUE TITLE
add page with CommonMark compatible software

### ISSUE THREAD

**Issue by vassudanagunta** [commonmark/markdownhelp#12]
A page listing tools and platforms that support CommonMark would...

1. give users an idea of the breadth of CommonMark support. This will help them decide whether to use it. 
2. help them find the CommonMark supporting tools they need.
3. help drive adoption of CommonMark.

It could be a simple list like the following, or a table with fields such as software/platform category, version of CommonMark supported, etc.

- [GitHub](https://talk.commonmark.org/t/github-is-now-using-commonmark-and-a-modified-version-of-cmark/2365)
- Hugo
- [Discourse](https://talk.commonmark.org/t/discourse-is-migrating-to-commonmark/2476)
- Typora
- [Ghost](https://talk.commonmark.org/t/ghost-1-0-uses-commonmark/2551)
- [GhostWriter](https://talk.commonmark.org/t/ghostwriter-a-new-markdown-editor-for-windows-and-linux-with-commonmark-support/1859)

**Comment by jgm** [comment]
Have you seen
https://github.com/commonmark/CommonMark/wiki ?
If it seems incomplete, feel free to add.

+++ Vas Sudanagunta [Oct 26 17 04:55 ]:

**Comment by coding-horror** [comment]
hmm maybe we should link to that wiki from the homepage though?

**Comment by vassudanagunta** [comment]
I'll plug any missing things that I know of. 

Perhaps a table is overkill. But that reminds me, you two  @jgm @coding-horror might find [this table comparing various lightweight markup syntaxes](http://hyperpolyglot.org/lightweight-markup) useful as you are considering extensions to CommonMark after 1.0 releases.
