### ISSUE TITLE
last exercise

### ISSUE THREAD

**Issue by orchid00** [commonmark/markdownhelp#13]
in the last exercise

why is bon apetit! also idented? it is not part of the last item.

**Comment by coding-horror** [comment]
I guess that's more of a philosophical question, is part of step 3 to eat the food? ;)

The instructions do say "content under each numbered item" so the implicit instruction is to indent it all.

**Comment by orchid00** [comment]
I will accept that.


  1. Dec 22nd
  2. Dec 23rd
  3. Dec 24th
  Merry Christmas!
