### ISSUE TITLE
Misleading wording in "Paragraphs" section

### ISSUE THREAD

**Issue by WillRieske** [commonmark/markdownhelp#20]
The phrase "Format this poem so the lines end exactly as shown in the editor" is confusing.  
If I change the editor contents to visually match the initial state of the preview pane, the phrase's requirement is fulfilled, yet the tutorial does not recognize this as a pass condition (see screenshot).  
Recommend rewording.
![Capture of paragraph section](https://user-images.githubusercontent.com/6845646/55573896-1adb9180-56d9-11e9-8073-8135ee9fd291.PNG)

**Comment by coding-horror** [comment]
Oh I see you think we should say "preview" instead of editor. Fair enough let me change that.

**Comment by coding-horror** [comment]
ok that is done thanks!
