### ISSUE TITLE
Example 531 doesn't match spec

### ISSUE THREAD

**Issue by jo-so** [commonmark/markdownhelp#23]
The [spec for example 531](https://github.com/commonmark/commonmark-spec/blob/master/spec.txt#L8025) contains a `*` at the end, that is missing on the [website](https://spec.commonmark.org/0.29/#example-531).

``````````````````````````````````````
```````````````````````````````` example
[foo *bar][ref]*

[ref]: /uri
.
<p><a href="/uri">foo *bar</a>*</p>
````````````````````````````````
``````````````````````````````````````

and

![grafik](https://user-images.githubusercontent.com/23032146/68542942-7a0d2d00-03b1-11ea-99c4-5bc38d43366b.png)

**Comment by jgm** [comment]
This was a bug in the spec that has been fixed since the last release (reflected on the website).  See commit 600070883209e8042e17cd82b3870d473b581907

 It will be fixed when we put out a new release.

**Comment by waldyrious** [comment]
> See commit 600070883209e8042e17cd82b3870d473b581907

Link for convenience: https://github.com/commonmark/commonmark-spec/commit/600070883209e8042e17cd82b3870d473b581907
