### ISSUE TITLE
Anchor links will always be tied to a specific spec version

### ISSUE THREAD

**Issue by michael-hawker** [commonmark/markdownhelp#24]
I realized when linking to the spec, that it'd always will be tied to the specific version that I'm looking at.  It'd be great if on the spec listing page when I click on `current` that the url contains `current` as well instead of the version number, i.e.

```
https://spec.commonmark.org/current/#thematic-breaks
```

vs.

```
https://spec.commonmark.org/0.29/#thematic-breaks
```

without issuing the re-direct that breaks the anchor link.  I understand that sections may change (though I'd guess this is mostly unlikely with top-level sections), but it'd be great to be able to point to the most up-to-date information when needed.

**Comment by jgm** [comment]
I'm more worried about the links to the examples than the links to the sections.
Example numbering will almost always change between versions, so the approach you're recommending would lead to many misleading links.  You can just change the links manually.
