### ISSUE TITLE
Incorrect rendering on commonmark dingus

### ISSUE THREAD

**Issue by anand-avinash** [commonmark/markdownhelp#25]
While trying out [Example 235](https://spec.commonmark.org/0.29/#example-235) on the dingus, I [found](https://spec.commonmark.org/dingus/?text=123.%20Good%0A%0A123456789%0A%0A123456789.%20Not%20Good%0A123456790.%20Again%20not%20Good) that an ordered list with the list marker having 4+ digits is rendered only with last 4 digits of the marker. The issue is related to the fixed position of list delimiter in the preview box. 
![Capture](https://user-images.githubusercontent.com/36325275/81735369-969a3700-94b2-11ea-9f67-a464b52893f8.PNG)

**Comment by coding-horror** [comment]
That's a CSS issue, really has nothing to do with commonmark.

**Comment by anand-avinash** [comment]
I thought it was within the scope of the CommonMark web page.

**Comment by coding-horror** [comment]
well yes, but a 10-digit numbered list is not exactly a layout priority ;)

**Comment by jgm** [comment]
Is there a specific CSS change you think would help?  CSS is pretty minimal, and I don't see anything adding this restriction; maybe it comes from bootstrap defaults?
