### ISSUE TITLE
dingus doesn't work

### ISSUE THREAD

**Issue by Kratacoa** [commonmark/markdownhelp#28]
Preview doesn't work on latest Linux version of Firefox (81), nor any other scripted buttons.

**Comment by jgm** [comment]
It works for me with latest Firefox on macOS.
Can anyone else confirm the issue on linux?

**Comment by coding-horror** [comment]
![image](https://user-images.githubusercontent.com/1522517/95255512-58d9da00-07d6-11eb-899d-f9b479173b79.png)

Seems OK for me on latest Firefox for Windows 10 as well?

**Comment by Kratacoa** [comment]
Now it works fine for me as well. No clue what's changed, I didn't do any updates.
I'll close the issue then (given also scarce information on the issue provided by me).
