### ISSUE TITLE
Problem with tutorial lesson 7 - links

### ISSUE THREAD

**Issue by SJaffa** [commonmark/markdownhelp#31]
The last exercise on links (part 7 - making links to hurricanes) doesn't accept the correct answer as the link given in the question doesn't match the one shown in the hint.

**Comment by coding-horror** [comment]
ah dang we must have missed this when the goo.gl was removed.

**Comment by coding-horror** [comment]
OK

https://github.com/commonmark/commonmark-web/pull/30

resolved in

https://github.com/commonmark/commonmark-web/commit/5d21aca4d9ed0cf93aea28676833eca6e4df0a83

**Comment by coding-horror** [comment]
Thanks for reporting, sorry about that!! We should have tested it.. sigh..
