### ISSUE TITLE
http://code.commonmark.org/ link is broken

### ISSUE THREAD

**Issue by john-cj** [commonmark/markdownhelp#41]
On https://commonmark.org/ there is a hyperlink http://code.commonmark.org/. That link seems to be broken.

**Comment by waldyrious** [comment]
That link works for me (it redirects to https://github.com/commonmark/commonmark-spec). That said, it should probably be updated to use HTTPS.

**Comment by jgm** [comment]
Works for me too.  @coding-horror would be the one who could update this.

**Comment by coding-horror** [comment]
I have fixed it, apologies for the oversight / delay and thank you for bringing it to my attention!

**Comment by gabrielsroka** [comment]
the https link is broken again, but the http one works
