### ISSUE TITLE
The very last line in the last exercise should not be indented

### ISSUE THREAD

**Issue by madsh** [commonmark/markdownhelp#60]
Hi, 

We tried your awsome learning experiences, but we believe the last exercise has a small flaw. 

The line containing "Bon appetit!" needs to be indented under the last item on the ordered list for the test to complete. 

It seems like the greeting is not a sub-element of the last orded item "Serve".

**Comment by coding-horror** [comment]
thanks for the feedback! This is intentional, e.g. "content under each numbered item" and "Bon appetit!" counts as that; it is the end of step 3.

**Comment by madsh** [comment]
I get your point… but I could not convince my 10-year old kid about it. He still thinks content is a synonym for ingredients… and the greeting does not go into the food. He is usually right about must things, that I take for granted otherwise :-) MvhMads ***@***.*** 3. mar. 2023 kl. 01.44 skrev Jeff Atwood ***@***.***>:﻿
thanks for the feedback! This is intentional, e.g. "content under each numbered item" and "Bon appetit!" counts as that; it is the end of step 3.
